---
name: Build and Push Image

on:
  workflow_call:
    inputs:
      push:
        description: "Push image to the container registry"
        type: boolean
        default: true
      platforms:
        description: "Platform(s) for build"
        type: string
        default: amd64
        required: false

env:
  IMAGE_NAME: ${{ github.event.repository.name }}
  IMAGE_TAGS: latest ${{ github.sha }}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ghcr.io/${{ github.repository }}
          platforms: ${{ inputs.platforms }}
          tags: ${{ env.IMAGE_TAGS }}
          oci: true
          containerfiles: |
            ./Containerfile


      - name: Push to ghcr.io
        id: push-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        if: ${{ inputs.push == true }}
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_TAGS }}
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
